// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btfdkfpmgqzezgyunpek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZmRrZnBtZ3F6ZXpneXVucGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NTczMDksImV4cCI6MjA4MDQzMzMwOX0.RSVwgQMOOv05CgPuflOkLgUhvuly3NIxwzz5pjWRhQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);