// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ostaldphsoiputdakucu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zdGFsZHBoc29pcHV0ZGFrdWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTcwMzksImV4cCI6MjA2MDE3MzAzOX0.Z3biLgFnQt765BkAgXeusA3ZoGzqFaZnFDqji9LCZcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);